### ISSUE TITLE
Build packages can`t find patterns 

### ISSUE THREAD

**Issue by neochapay** [mer-hybris/droid-hal-configs#74]
When i start build_packages i have error:
`checking for /home/user/mer/android/droid/droid-local-repo/device/droid-configs/*-patterns*.rpm...
Error: no patterns RPM found`
Because patterns RPM in /home/user/mer/android/droid/droid-local-repo/device/ directory

**Comment by Thaodan** [comment]
Closing this issue, it should be obsolete by now.
